version: 2.1
executors:
  test:
    docker:
      - image: "circleci/golang:1.13"
  docker-publisher:
    environment:
      IMAGE_NAME: martenseemann/quic-go-interop
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  test:
    executor: test
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: |
            cd interop/http09/
            go get github.com/onsi/ginkgo/ginkgo
            go get github.com/onsi/gomega
            ginkgo -race -r -v -randomizeAllSpecs -trace
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build . -t $IMAGE_NAME:latest
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load archived Docker image 
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish quic-go-interput
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
